In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
path=r"C:\Users\nobod\Downloads\Visadataset - Visadataset (1).csv"
visa_df=pd.read_csv(path)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [4]:
cat=visa_df.select_dtypes(include='object')
cat

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,region_of_employment,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,West,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,Northeast,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,West,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,West,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,South,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,South,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,Northeast,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,South,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,West,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,Midwest,Year,Y,Certified

In [6]:
cat=visa_df.select_dtypes(include='object').columns
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [5]:
num=visa_df.select_dtypes(exclude='object')
num

       no_of_employees  yr_of_estab  prevailing_wage
0                14513         2007         592.2029
1                 2412         2002       83425.6500
2                44444         2008      122996.8600
3                   98         1897       83434.0300
4                 1082         2005      149907.3900
...                ...          ...              ...
25475             2601         2008       77092.5700
25476             3274         2006      279174.7900
25477             1121         1910      146298.8500
25478             1918         1887       86154.7700
25479             3195         1960       70876.9100

[25480 rows x 3 columns]

In [7]:
num=visa_df.select_dtypes(exclude='object').columns
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

In [ ]:
- We already performed analysis on content

In [11]:
keys=visa_df['continent'].value_counts().keys()
values=visa_df['continent'].value_counts().values
pd.DataFrame(zip(keys,values),columns=['continent','count'])

       continent  count
0           Asia  16861
1         Europe   3732
2  North America   3292
3  South America    852
4         Africa    551
5        Oceania    192

In [13]:
#case_status

keys=visa_df['case_status'].value_counts().keys()
values=visa_df['case_status'].value_counts().values
pd.DataFrame(zip(keys,values),columns=['status','count'])

      status  count
0  Certified  17018
1     Denied   8462

**To find the number of certified and denied applicants of continent wise**

In [19]:
Cert_count=[]
Denied_count=[]

#step1- retrieve continent column

visa_df['continent']

0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
          ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia
Name: continent, Length: 25480, dtype: object

In [18]:
#step2-- continent is Asia

con1=visa_df['continent']=='Asia'
con1

0         True
1         True
2         True
3         True
4        False
         ...
25475     True
25476     True
25477     True
25478     True
25479     True
Name: continent, Length: 25480, dtype: bool

In [17]:
#Step3- Retrieve case status column

visa_df['case_status']

0           Denied
1        Certified
2           Denied
3           Denied
4        Certified
           ...
25475    Certified
25476    Certified
25477    Certified
25478    Certified
25479    Certified
Name: case_status, Length: 25480, dtype: object

In [20]:
#step4- case sttaus==certified

con2=visa_df['case_status']=='Certified'
con2

0        False
1         True
2        False
3        False
4         True
         ...
25475     True
25476     True
25477     True
25478     True
25479     True
Name: case_status, Length: 25480, dtype: bool

In [21]:
#Step-5 case sttaus== denied

con3=visa_df['case_status']=='Denied'
con3

0         True
1        False
2         True
3         True
4        False
         ...
25475    False
25476    False
25477    False
25478    False
25479    False
Name: case_status, Length: 25480, dtype: bool

In [22]:
#Step-6

cert_con=con1&con2
cert_con

0        False
1         True
2        False
3        False
4        False
         ...
25475     True
25476     True
25477     True
25478     True
25479     True
Length: 25480, dtype: bool

In [23]:
#Step-7

Denied_con=con1&con3
Denied_con

0         True
1        False
2         True
3         True
4        False
         ...
25475    False
25476    False
25477    False
25478    False
25479    False
Length: 25480, dtype: bool

In [31]:
#Step-8- count of certi_con -- Asia continent-- certified column

count_certified=visa_df[cert_con]
count_certified

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.65,Year,Y,Certified
5,EZYV06,Asia,Master's,Y,N,2339,2012,South,78252.14,Year,Y,Certified
6,EZYV07,Asia,Bachelor's,N,N,4985,1994,South,53635.39,Year,Y,Certified
8,EZYV09,Asia,Bachelor's,N,N,4810,2012,Midwest,74362.19,Year,Y,Certified
10,EZYV11,Asia,Master's,N,N,2465,2004,Midwest,83588.56,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.57,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.79,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.85,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.77,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.91,Year,Y,Certified

In [32]:
len(count_certified)

11012

In [28]:
#Step-9- count of certi_con

count_denied=visa_df[Denied_con]
count_denied

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
11,EZYV12,Asia,High School,Y,N,4069,2005,Northeast,70813.0900,Year,Y,Denied
15,EZYV16,Asia,High School,Y,N,4897,1987,West,74108.0200,Year,Y,Denied
...,...,...,...,...,...,...,...,...,...,...,...,...
25450,EZYV25451,Asia,Bachelor's,N,N,3312,2009,Northeast,682.1048,Hour,Y,Denied
25452,EZYV25453,Asia,High School,N,N,70,1995,Northeast,84833.8900,Year,Y,Denied
25454,EZYV25455,Asia,Bachelor's,N,N,1316,2007,South,62844.9700,Year,Y,Denied
25459,EZYV25460,Asia,High School,Y,N,4727,1990,Midwest,53952.8400,Year,Y,Denied
25461,EZYV25462,Asia,Master's,Y,N,2861,2004,West,54.9196,Hour,Y,Denied

In [30]:
len(count_denied)

5849

In [40]:
cert_count,deni_count=[],[]
for i in visa_df['continent'].unique():
    con1=visa_df['continent']==i
    con2=visa_df['case_status']=='Certified'
    con3=visa_df['case_status']=='Denied'
    cert_con=con1&con2
    Denied_con=con1&con3
    count_certified=len(visa_df[cert_con])
    count_denied=len(visa_df[Denied_con])
    cert_count.append(count_certified)
    deni_count.append(count_denied)

In [41]:
cert_count,deni_count

([11012, 397, 2037, 2957, 493, 122], [5849, 154, 1255, 775, 359, 70])

In [47]:
data=zip(cert_count,deni_count)
cols=visa_df['case_status'].unique()
idx=visa_df['continent'].unique()
pd.DataFrame(data,index=idx,columns=cols)

               Denied  Certified
Asia            11012       5849
Africa            397        154
North America    2037       1255
Europe           2957        775
South America     493        359
Oceania           122         70

In [48]:
#in above Denied came frst.. to avoid that reverse cols usng list

data=zip(cert_count,deni_count)
cols=visa_df['case_status'].unique()[::-1]
idx=visa_df['continent'].unique()
pd.DataFrame(data,index=idx,columns=cols)

               Certified  Denied
Asia               11012    5849
Africa               397     154
North America       2037    1255
Europe              2957     775
South America        493     359
Oceania              122      70

**cross tab**

- to categorize continent wise -- certified & denied, we cn use **CROSS TAB** method

In [52]:
col1=visa_df['continent']
col2=visa_df['case_status']
pd.crosstab(index=col1
            ,columns=col2)

case_status    Certified  Denied
continent
Africa               397     154
Asia               11012    5849
Europe              2957     775
North America       2037    1255
Oceania              122      70
South America        493     359

**PIVOT TABLE**

In [53]:
col1=visa_df['continent']
col2=visa_df['case_status']
visa_df.pivot_table(index=col1
            ,columns=col2)

TypeError: agg function failed [how->mean,dtype->object]

In [58]:
#gettg error as aggregation fun failed

col1=visa_df['continent']
col2=visa_df['case_status']
visa_df.pivot_table(index=col1
            ,columns=col2,
           aggfunc='size')

case_status    Certified  Denied
continent
Africa               397     154
Asia               11012    5849
Europe              2957     775
North America       2037    1255
Oceania              122      70
South America        493     359

**GROUP BY**

In [61]:
visa_df.groupby(['continent','case_status']).size().unstack()

case_status    Certified  Denied
continent
Africa               397     154
Asia               11012    5849
Europe              2957     775
North America       2037    1255
Oceania              122      70
South America        493     359