- Generally ML models are developed by maths

- convert categorical column to Numerical columns

- Here we transform the data

- this method is called encoding

- feature ANalysis: 5 sessions

- Feature Engineering : Transform the data

- Feature Selection : Machine Learning

- Before Model Development 

- we will do EDA : Exploratory data analysis

    - Features (Columns) Analysis

        - Categorcial, Numerical , Outlier Analysis, Bivariate, Multivariate

        - we will get insights

    - feature engineering

        - We will modify the data

        - Models developed by maths

        - Encoding -- Convert categorical data to Numercial variables

        - Scaling- All the numerical columns makes under one scale

        - Transformations - All the maths developed by assumption data follows normal distribution

            -  Convert skewed distribution to Normal

    - feature selection

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
path=r"C:\Users\nobod\OneDrive\Data Science_2025\Datafiles\Visadataset - Visadataset (1).csv"
visa_df=pd.read_csv(path)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [3]:
cat=visa_df.select_dtypes(include='object').columns
cat

num=visa_df.select_dtypes(exclude='object').columns
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

In [4]:
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [5]:
#create a dict assign a number start with zero
#for each labels based on alphabetical order

d={'Certified':0,'Denied':1}
d

{'Certified': 0, 'Denied': 1}

In [6]:
#map the dictionary with column

visa_df['case_status'].map(d)

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [7]:
visa_df['case_status']=visa_df['case_status'].map(d)  #In case_status column certfied is replaced by 0 & denied by 1

In [8]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [9]:
visa_df['continent'].unique()

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [10]:
d={'Asia':0,'Africa':1,'North America':2,'Europe':3, 'South America':4,'Oceania':5}
d

{'Asia': 0,
 'Africa': 1,
 'North America': 2,
 'Europe': 3,
 'South America': 4,
 'Oceania': 5}

In [11]:
visa_df['continent'].map(d)

0        0
1        0
2        0
3        0
4        1
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: continent, Length: 25480, dtype: int64

In [12]:
visa_df['continent']=visa_df['continent'].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,0,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,0,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,0,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,1,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,0,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,0,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,0,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,0,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [13]:
labels=visa_df['region_of_employment'].unique()
d={}
for i in range(len(labels)):
    key=labels[i]
    d[key]=i
d

{'West': 0, 'Northeast': 1, 'South': 2, 'Midwest': 3, 'Island': 4}

In [14]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,0,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,0,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,0,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,1,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,0,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,0,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,0,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,0,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [15]:
cat=visa_df.select_dtypes(include='object').columns
for i in cat[1:]:
    uniq=visa_df[i].unique()
    d={uniq[i]:i for i in range(len(uniq))}   # uniq[i]:i -- key:value 
    visa_df[i]=visa_df[i].map(d)
visa_df

#It converts all categorical clmn values to numercial values

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0,0,0,0,14513,2007,0,592.2029,0,0,1
1,EZYV02,0,1,1,0,2412,2002,1,83425.6500,1,0,0
2,EZYV03,0,2,0,1,44444,2008,0,122996.8600,1,0,1
3,EZYV04,0,2,0,0,98,1897,0,83434.0300,1,0,1
4,EZYV05,1,1,1,0,1082,2005,2,149907.3900,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,2,1,1,2601,2008,2,77092.5700,1,0,0
25476,EZYV25477,0,0,1,0,3274,2006,1,279174.7900,1,0,0
25477,EZYV25478,0,1,1,0,1121,1910,2,146298.8500,1,1,0
25478,EZYV25479,0,1,1,1,1918,1887,0,86154.7700,1,0,0
25479,EZYV25480,0,2,1,0,3195,1960,3,70876.9100,1,0,0

**Scikit-learn or sklearn**

- All preprocessing Feature engineering & feature selection

- Missing values imputation

- Data transformation

- ML model development

- ML model evaluation i.e., metrics

**Step-1** : Load the package

**Step-2** : Save the package

**Step-3** : Apply fit transform

- package name : **sklearn**

    - Class name : **Preprocessing**

          - Method_name : **LabelEncoder**

In [16]:
#read the data

path=r"C:\Users\nobod\OneDrive\Data Science_2025\Datafiles\Visadataset - Visadataset (1).csv"
visa_df=pd.read_csv(path)
visa_df

#load pkg
from sklearn.preprocessing import LabelEncoder

#save the pkg

le=LabelEncoder()

#apply fit transform 

visa_df['case_status_1']=le.fit_transform(visa_df['case_status'])   # 
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status,case_status_1
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified,0

In [17]:
visa_df=pd.read_csv(path)
from sklearn.preprocessing import LabelEncoder
for i in cat[1:]:
    le=LabelEncoder()
    visa_df[i]=le.fit_transform(visa_df[i])  #visa_df['case_status_1']=le.fit_transform(visa_df['case_status'])  
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,2,0,0,14513,2007,4,592.2029,0,1,Denied
1,EZYV02,Asia,3,1,0,2412,2002,2,83425.6500,3,1,Certified
2,EZYV03,Asia,0,0,1,44444,2008,4,122996.8600,3,1,Denied
3,EZYV04,Asia,0,0,0,98,1897,4,83434.0300,3,1,Denied
4,EZYV05,Africa,3,1,0,1082,2005,3,149907.3900,3,1,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,0,1,1,2601,2008,3,77092.5700,3,1,Certified
25476,EZYV25477,Asia,2,1,0,3274,2006,2,279174.7900,3,1,Certified
25477,EZYV25478,Asia,3,1,0,1121,1910,3,146298.8500,3,0,Certified
25478,EZYV25479,Asia,3,1,1,1918,1887,4,86154.7700,3,1,Certified
25479,EZYV25480,Asia,0,1,0,3195,1960,1,70876.9100,3,1,Certified

In [18]:
visa_df['education_of_employee'].unique()

array([2, 3, 0, 1])

**Inverse Transform**

In [19]:
visa_df=pd.read_csv(path)
le=LabelEncoder()
encoded_labels=le.fit_transform(visa_df['education_of_employee'])
decoded_labels=le.inverse_transform(encoded_labels)
print(encoded_labels[:5])
print(decoded_labels[:5])

[2 3 0 0 3]
['High School' "Master's" "Bachelor's" "Bachelor's" "Master's"]

In [20]:
pd.DataFrame(zip(encoded_labels,decoded_labels))

       0            1
0      2  High School
1      3     Master's
2      0   Bachelor's
3      0   Bachelor's
4      3     Master's
...   ..          ...
25475  0   Bachelor's
25476  2  High School
25477  3     Master's
25478  3     Master's
25479  0   Bachelor's

[25480 rows x 2 columns]

In [21]:
visa_df=pd.read_csv(path)
le=LabelEncoder()
s1=le.fit_transform(visa_df['education_of_employee'])
s2=le.inverse_transform(s1)
s2

s1[:5]
s2[:5]
pd.DataFrame(zip(s1,s2))

       0            1
0      2  High School
1      3     Master's
2      0   Bachelor's
3      0   Bachelor's
4      3     Master's
...   ..          ...
25475  0   Bachelor's
25476  2  High School
25477  3     Master's
25478  3     Master's
25479  0   Bachelor's

[25480 rows x 2 columns]

**OneHotEncoder**

- One hot means at a time only one will be **ON** and other will be **OFF**

- It creates more columns based on labels

- Ex-- Case_status has two labels 1. Certified 2. Denied

- Total Visa_df has 12 columns

- When we apply OneHotEncoder two extra columns will be created

- 1. Case_status_Certified  2.case_status_Denied  Total columns-14
 
     |case_status|Certified|Denied|
     |-|-|-|
     |Certified|1|0|
     |Denied|0|1|
     |Denied|0|1|
     |Certified|1|0|

**using markdown**

  |col1|col2|col3|
  |-|-|-|
  |Col2|0|1|
  |col3|0|1|

**pd.get_dummies**

In [23]:
import pandas as pd
visa_df=pd.read_csv(path)
pd.get_dummies(visa_df)

,no_of_employees,yr_of_estab,prevailing_wage,case_id_EZYV01,case_id_EZYV02,case_id_EZYV03,case_id_EZYV04,case_id_EZYV05,case_id_EZYV06,case_id_EZYV07,...,region_of_employment_South,region_of_employment_West,unit_of_wage_Hour,unit_of_wage_Month,unit_of_wage_Week,unit_of_wage_Year,full_time_position_N,full_time_position_Y,case_status_Certified,case_status_Denied
0,14513,2007,592.2029,True,False,False,False,False,False,False,...,False,True,True,False,False,False,False,True,False,True
1,2412,2002,83425.6500,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,True,True,False
2,44444,2008,122996.8600,False,False,True,False,False,False,False,...,False,True,False,False,False,True,False,True,False,True
3,98,1897,83434.0300,False,False,False,True,False,False,False,...,False,True,False,False,False,True,False,True,False,True
4,1082,2005,149907.3900,False,False,False,False,True,False,False,...,True,False,False,False,False,True,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,2601,2008,77092.5700,False,False,False,False,False,False,False,...,True,False,False,False,False,True,False,True,True,False
25476,3274,2006,279174.7900,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,True,False
25477,1121,1910,146298.8500,False,False,False,False,False,False,False,...,True,False,False,False,False,True,True,False,True,False
25478,1918,1887,86154.7700,False,False,False,False,False,False,False,...,False,True,False,False,False,True,False,True,True,False
25479,3195,1960,70876.9100,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,True,False

In [28]:
#to drop case id

import pandas as pd
visa_df=pd.read_csv(path)
visa_df.drop('case_id',axis=1,inplace=True)
pd.get_dummies(visa_df,dtype='int')

,no_of_employees,yr_of_estab,prevailing_wage,continent_Africa,continent_Asia,continent_Europe,continent_North America,continent_Oceania,continent_South America,education_of_employee_Bachelor's,...,region_of_employment_South,region_of_employment_West,unit_of_wage_Hour,unit_of_wage_Month,unit_of_wage_Week,unit_of_wage_Year,full_time_position_N,full_time_position_Y,case_status_Certified,case_status_Denied
0,14513,2007,592.2029,0,1,0,0,0,0,0,...,0,1,1,0,0,0,0,1,0,1
1,2412,2002,83425.6500,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
2,44444,2008,122996.8600,0,1,0,0,0,0,1,...,0,1,0,0,0,1,0,1,0,1
3,98,1897,83434.0300,0,1,0,0,0,0,1,...,0,1,0,0,0,1,0,1,0,1
4,1082,2005,149907.3900,1,0,0,0,0,0,0,...,1,0,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,2601,2008,77092.5700,0,1,0,0,0,0,1,...,1,0,0,0,0,1,0,1,1,0
25476,3274,2006,279174.7900,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
25477,1121,1910,146298.8500,0,1,0,0,0,0,0,...,1,0,0,0,0,1,1,0,1,0
25478,1918,1887,86154.7700,0,1,0,0,0,0,0,...,0,1,0,0,0,1,0,1,1,0
25479,3195,1960,70876.9100,0,1,0,0,0,0,1,...,0,0,0,0,0,1,0,1,1,0

In [ ]:
#read data
#pkg -- from sklear.preprocessing import sklearn
#save pk-- le=LabelEncoder()
#le.fit_transform(visa_df['column'])

**sept 19**

**LabelEncoder vs OnehotEncoder**

- Generally we dont have a relation between input columns

- we need both input columns which are not correlated to each other

- we need both input columns which are independent (X,Y) to each other

- We need both columns which are perpendicular to each other

- We need both columns which are orthogonal to each other

- We need both columns which are 90 degrees phase shift to each other

- OneHotEncoder will achieve above..

- But OneHotEncoder creates new columns

    - Columns are increased means dimensions are increased
 
    - More dimension data need more processing time
 
    - More dimension data need more infra
 
    - This is called **Curse of Dimensionality**