In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
path=r"C:\Users\nobod\OneDrive\Data Science_2025\Datafiles\Visadataset - Visadataset (1).csv"
visa_df=pd.read_csv(path)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [4]:
cat=visa_df.select_dtypes(include='object').columns
print("categorical columns:",cat)
num=visa_df.select_dtypes(exclude='object').columns
print("numerical columns:",num)

categorical columns: Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')
numerical columns: Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

In [11]:
wage_data=visa_df['prevailing_wage']
wage_data

0           592.2029
1         83425.6500
2        122996.8600
3         83434.0300
4        149907.3900
            ...
25475     77092.5700
25476    279174.7900
25477    146298.8500
25478     86154.7700
25479     70876.9100
Name: prevailing_wage, Length: 25480, dtype: float64

In [12]:
wage_data.mean()

74455.81459209183

In [46]:
mean=round(np.mean(wage_data),2)
mean

74455.81

In [33]:
count=wage_data.count()
count

25480

In [32]:
min=wage_data.min()
min

2.1367

In [31]:
max=wage_data.max()
max

319210.27

In [45]:
median=round(wage_data.median(),2)
median

70308.21

In [44]:
n_25p=np.percentile(wage_data,25)
n_25p=round(n_25p,2)
n_25p

34015.48

In [43]:
n_50p=np.percentile(wage_data,50)
n_50p=round(n_50p,2)
n_50p

70308.21

In [42]:
n_75p=np.percentile(wage_data,75)
n_75p=round(n_75p,2)
n_75p

107735.51

In [38]:
max_value=round(wage_data.max(),2)
max_value

319210.27

In [37]:
min_value=round(wage_data.min(),2)
min_value

2.14

In [55]:
values=[mean,median,max_value,min_value,count]

pd.DataFrame(values,
            index=['MEAN','MEDIAN','MAX','MIN','COUNT'],
            columns=['prevailing wage'])

        prevailing wage
MEAN           74455.81
MEDIAN         70308.21
MAX           319210.27
MIN                2.14
COUNT          25480.00